apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.service_name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "edgelake-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metadata.service_type }}
  selector:
    {{- include "edgelake-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: tcp-server
    protocol: TCP
    port: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
    targetPort: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
    {{- if eq .Values.metadata.service_type "NodePort" }}
    nodePort: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
    {{- end }}
  - name: rest-api
    protocol: TCP
    port: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
    targetPort: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
    {{- if eq .Values.metadata.service_type "NodePort" }}
    nodePort: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
    {{- end }}
  {{- if .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
  - name: mqtt-broker
    protocol: TCP
    port: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
    targetPort: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
    {{- if eq .Values.metadata.service_type "NodePort" }}
    nodePort: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
    {{- end }}
  {{- end }}
