apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgelake-operator-controller
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: edgelake-operator
    app.kubernetes.io/component: controller
